name: k24-default-bitstreams
base: core24
adopt-info: version
summary: Load a default bitstream to fpga device on boot
description: |
  This snap application connects with fpgad to load a bitstream to the fpga0 device.
  The contained bitstream is a fan controller for the K*26* series of Xilinx boards.
grade: devel
confinement: strict
plugs:
  fpgad-dbus:
    interface: dbus
    bus: system
    name: com.canonical.fpgad
apps:
  k24-default-bitstreams:
    command: bin/k24_default_bitstreams
    daemon: oneshot
    plugs:
      - fpgad-dbus
    restart-condition: always
    start-timeout: 30s
    install-mode: disable
parts:
  version:
    plugin: nil
    source: .
    build-snaps:
      - jq
    override-pull: |
      craftctl default
      current_version=0.1.0 # todo: automatic updating of version
      craftctl set version="$current_version+git$(date +'%Y%m%d').$(git describe --always --exclude '*')"
  k24-default-bitstreams:
    build-packages:
      - pkg-config
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-0
    plugin: cmake
    source: ./k24-default-bitstreams
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/ # Otherwise the DESTDIR is relative to $SNAPCRAFT_PART_INSTALL/usr/local/
  bitstream-data:
    plugin: dump
    source: https://github.com/Xilinx/kria-base-firmware
    source-type: git
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/data/k24-starter-kits
      cp k24_starter_kits/k24_starter_kits.bit $SNAPCRAFT_PART_INSTALL/data/k24-starter-kits/
      cp LICENSE-BINARIES $SNAPCRAFT_PART_INSTALL/data/k24-starter-kits/
